### PR TITLE
Automate sourcing of westpa.sh in activate.d

### PR DESCRIPTION
**Pull request by burntyellow**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by burntyellow** [comment]
@conda-forge-admin, please rerender

**Comment by burntyellow** [comment]
@synapticarbors What are the steps for merging the pull request?  I've successfully tested the recipe locally yesterday and upload/conda install from the kimwong channel.

**Comment by synapticarbors** [comment]
I'll try to take a look at this soon

**Comment by synapticarbors** [comment]
- Since this is the same version of westpa but we've made a change to the recipe, we should increment the `build` number.

- Should we have any sort of clean-up of the environment variable in a deactivate script? I don't think it is strictly necessary because most people aren't working in multiple westpa environments in the same open process and the `westpa.sh` should overwrite the relevant environment variables when the environment switches, but maybe it would be a good idea just in terms of proper clean-up. See https://github.com/conda-forge/ambertools-feedstock/blob/master/recipe/deactivate.sh

In terms of merging, once everything is the way we want it, just merging the PR will kickstart all of the CI machinery that pushes the changes up to the conda-forge channel.

**Comment by burntyellow** [comment]
I've updated the version number.  However, I forgot to branch my fork.  Is that what is causing the errors.  Should I start over and branch my fork before issuing a new pull request?

Regarding the scripts in deactive.d, what do you suggest?  Should I simply unset the variables that were set in active.d?

**Comment by synapticarbors** [comment]
Oops, sorry I wasn't 100% explicit about the build number. I meant the one in the `meta.yaml`:

https://github.com/conda-forge/westpa-feedstock/blob/3234aec38b9b0367a3ab0f50a9b79caec157b6ef/recipe/meta.yaml#L15

Since there was no change to the package and just the recipe, it's not necessary to spin out a new westpa release.

**Comment by synapticarbors** [comment]
If you have a new package release (the version of westpa changes), then you reset the `build` number in the `meta.yaml` to `0`. If the package release stays the same, but you're making a change to the recipe (e.g. fixing a dependency version, adding an activation script, etc -- something about how what is distributed through conda-forge behaves), then you increment the `build` number in the `meta.yaml`.

**Comment by burntyellow** [comment]
That makes sense.  Multi-tasking too much at once.  I don't know how the merge works; don't see a merge button.

**Comment by synapticarbors** [comment]
@burntyellow I just wanted to check in how you want to proceed with this. Do you want to roll back the `2020.02` to `2020.01`, or just keep it? If using `2020.02` the `build` in the `meta.yaml` should be changed to `0`, if we use `2020.01` it should stay at `1`.

**Comment by synapticarbors** [comment]
@burntyellow I just wanted to check in how you want to proceed with this. Do you want to roll back the `2020.02` to `2020.01`, or just keep it? If using `2020.02` the `build` in the `meta.yaml` should be changed to `0`, if we use `2020.01` it should stay at `1`.

**Comment by synapticarbors** [comment]
@burntyellow I just wanted to check in how you want to proceed with this. Do you want to roll back the `2020.02` to `2020.01`, or just keep it? If using `2020.02` the `build` in the `meta.yaml` should be changed to `0`, if we use `2020.01` it should stay at `1`.

**Comment by synapticarbors** [comment]
apologies for the duplicate messages. Github was having a system-wide issue and it looks like it queued the failed submissions of the same comment each time I tried to send it

**Comment by burntyellow** [comment]
Reverted back to release "2020.01".  Left build number at 1. Let's not worry about the deactive.d script for now.

**Comment by burntyellow** [comment]
Is everything set to move forward?  I don't know what else needs to be done?

**Pull request merged**
