### PR TITLE
Update to latest version 2020.01

### PR DESCRIPTION
**Pull request by synapticarbors**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
@burntyellow -- trying to figure out why the re-render webservice is failing, so opening a duplicate PR here.

**Comment by synapticarbors** [comment]
It looks like we have an issue where `h5py` version 2.9 does not have a build available for python 3.8. Can we safely bump the h5py version to 2.10?

**Comment by synapticarbors** [comment]
Also for python 3.8, we're going to need `pyzmq` of at least `18.1.0`

**Comment by synapticarbors** [comment]
Also pyyaml >=5.2 for py38

**Comment by burntyellow** [comment]
After updating the min versions

     - h5py 2.10.*
     - pyyaml 5.2.*
     - pyzmq 18.1.*

I did a local conda build within a Python3.7 virtual env and also within a Python3.8 virtual env and both completed without error.

**Comment by synapticarbors** [comment]
@burntyellow a few questions:

- Should we shoot for using the latest release of pyzmq (19.0.0) and pyyaml (5.3.1)?
- Is there any functional testing we should do for these newer releases of the packages?
- Do we want to pin the version of cython for reproducibility since we're generating code?

**Comment by burntyellow** [comment]
I was able to build locally within conda environments py37 and py38.  I had to do a fresh install of anaconda3.7-2019.07 because my base env had pyzmq and pyyaml versions that threw conflicts even within the py37 environment.  Below are the current state of the dependencies.  I don't know who can test an actually WESTPA simulation.  I can do it but the earliest time frame may be Friday.

-------------------------
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - setuptools
    - python
    - cython
    - numpy 1.16.*
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - h5py 2.10.*
    - pyyaml 5.3.*
    - pyzmq 19.0.*
    - matplotlib-base
    - blessings 1.7.*

**Comment by burntyellow** [comment]
I was able to test my py37 and py38 builds successfully using the basic_nacl_amber tutorial.  I think we should push this out and enlist others to perform further testing.

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
Ok, I'm going to see if it needs to be re-rendered and then if that goes well, I'll merge this

**Comment by burntyellow** [comment]
@synapticarbors  Per your earlier suggestions, have you updated to

- pyyaml 5.3.*
- pyzmq 19.0.*

**Comment by synapticarbors** [comment]
@burntyellow thanks for the reminder. Just updated those now.

**Comment by synapticarbors** [comment]
@burntyellow good to merge or wait to resolve the issue we were discussing about activate scripts over email?

**Comment by burntyellow** [comment]
Let's merge and begin testing.  We'll deal with the activate scripts some more over email.

**Pull request merged**
