### PR TITLE
Py3

### PR DESCRIPTION
**Pull request by burntyellow**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
The license file is included in the source distribution, so this should be fine without further action. Often when building recipes off of pypi.io, upstream package maintainers do not have the license file specified in the `MANIFEST.in`, so the tarballs do not have the actual file, even if it is in the source repo. Here, since we are building from the github tarball that just includes everything, we're ok.

**Comment by synapticarbors** [comment]
Do we also want to consider the `matplotlib` issue raise in https://github.com/conda-forge/westpa-feedstock/pull/8, while we're doing this?

**Comment by burntyellow** [comment]
Sorry I posted on  the other PR.  Reposting below:

I skimmed through the discussions regarding matplotlib-base vs matplotlib. My grasp is that if westpa does not explicitly require pyqt, we should be importing matplotlib-base. Are you in agreement?

**Comment by mczwier** [comment]
Agreed

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by burntyellow** [comment]
Updated recipe to use matplotlib-base, tested recipe locally, pushed update reciped to py3 branch of westpa-feedstock fork.

**Comment by synapticarbors** [comment]
I'm not sure why the automatic re-render is not working. Either there is a backlog and it will do it eventually or something is broken. We can do it manually if need be.

**Comment by synapticarbors** [comment]
@burntyellow -- do you see something when you look at your PR to "allow edits by maintainers"? There is an error in the re-rendering webservice: 

https://github.com/conda-forge/westpa-feedstock/runs/527920947?check_suite_focus=true#step:3:306

**Comment by burntyellow** [comment]
@synapticarbors Yes.  Allow edits is checked.  I also just checked off re-render on the Checklist at the top ... not sure if that was the problem.

**Comment by synapticarbors** [comment]
Did you just check it, or had it been checked all along?

**Comment by synapticarbors** [comment]
The "allow edits from maintainers", is what I'm referring to. The other checklist shouldn't make a difference.

**Comment by burntyellow** [comment]
Allow edits by maintainers had been checked all along.

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by synapticarbors** [comment]
close in favor of #11

**Pull request closed without merging**
